package com.costavong.promptoverlay.pro;
import android.content.Context;
import com.costavong.promptoverlay.AppLanguage;
final class ProStrings {
    private static final String[][] WORDS={
        {"Close","Cerrar","Fermer","إغلاق"},
        {"Projects","Proyectos","Projets","المشاريع"},{"New project","Nuevo proyecto","Nouveau projet","مشروع جديد"},
        {"Teleprompter","Teleprompter","Téléprompteur","الملقّن"},{"Language","Idioma","Langue","اللغة"},
        {"Import video","Importar vídeo","Importer une vidéo","استيراد فيديو"},{"Rename","Renombrar","Renommer","إعادة تسمية"},
        {"Delete","Eliminar","Supprimer","حذف"},{"Open","Abrir","Ouvrir","فتح"},{"Back","Atrás","Retour","رجوع"},
        {"Save","Guardar","Enregistrer","حفظ"},{"Cancel","Cancelar","Annuler","إلغاء"},{"Clips","Clips","Clips","المقاطع"},
        {"Captions","Subtítulos","Sous-titres","الترجمة النصية"},{"Graphics","Gráficos","Éléments visuels","الرسومات"},
        {"Music","Música","Musique","الموسيقى"},{"Format","Formato","Format","التنسيق"},
        {"Preview","Vista previa","Aperçu","معاينة"},{"Export","Exportar","Exporter","تصدير"},
        {"Play clip","Reproducir clip","Lire le clip","تشغيل المقطع"},{"Pause","Pausar","Pause","إيقاف مؤقت"},
        {"Edited preview","Vista previa editada","Aperçu du montage","معاينة الفيديو المعدّل"},
        {"Play clip starts immediately. Edited preview includes captions, graphics and music.",
         "Reproducir clip empieza al instante. La vista previa editada incluye subtítulos, gráficos y música.",
         "La lecture du clip démarre immédiatement. L’aperçu du montage inclut les sous-titres, les éléments visuels et la musique.",
         "يبدأ تشغيل المقطع فورًا. تتضمن معاينة الفيديو المعدّل الترجمة النصية والرسومات والموسيقى."},
        {"Share","Compartir","Partager","مشاركة"},{"Save video","Guardar vídeo","Enregistrer la vidéo","حفظ الفيديو"},
        {"Project name","Nombre del proyecto","Nom du projet","اسم المشروع"},{"Edit selected clip","Editar clip seleccionado","Modifier le clip sélectionné","تحرير المقطع المحدد"},
        {"Split at playhead","Dividir aquí","Scinder au curseur","تقسيم عند المؤشر"},{"Move earlier","Mover antes","Déplacer avant","نقل إلى الأمام"},
        {"Move later","Mover después","Déplacer après","نقل إلى الخلف"},{"Delete clip","Eliminar clip","Supprimer le clip","حذف المقطع"},
        {"Start (seconds)","Inicio (segundos)","Début (secondes)","البداية (ثوانٍ)"},{"End (seconds)","Fin (segundos)","Fin (secondes)","النهاية (ثوانٍ)"},
        {"Speed","Velocidad","Vitesse","السرعة"},{"Crossfade into this clip (seconds)","Fundido a este clip (segundos)","Fondu vers ce clip (secondes)","تلاشي إلى هذا المقطع (ثوانٍ)"},
        {"Original sound volume (%)","Volumen original (%)","Volume du son original (%)","مستوى الصوت الأصلي (%)"},
        {"Mute original sound","Silenciar sonido original","Couper le son original","كتم الصوت الأصلي"},
        {"Brightness (-100 to 100)","Brillo (-100 a 100)","Luminosité (-100 à 100)","السطوع (-100 إلى 100)"},
        {"Contrast (%)","Contraste (%)","Contraste (%)","التباين (%)"},{"Saturation (%)","Saturación (%)","Saturation (%)","التشبع (%)"},
        {"Temperature (-100 to 100)","Temperatura (-100 a 100)","Température (-100 à 100)","الحرارة (-100 إلى 100)"},
        {"Crop left (%)","Recorte izquierdo (%)","Recadrage gauche (%)","قص اليسار (%)"},{"Crop top (%)","Recorte superior (%)","Recadrage haut (%)","قص الأعلى (%)"},
        {"Crop right (%)","Recorte derecho (%)","Recadrage droite (%)","قص اليمين (%)"},{"Crop bottom (%)","Recorte inferior (%)","Recadrage bas (%)","قص الأسفل (%)"},
        {"Green screen (experimental)","Pantalla verde (experimental)","Fond vert (expérimental)","الشاشة الخضراء (تجريبية)"},
        {"Green threshold (%)","Umbral verde (%)","Seuil du vert (%)","عتبة الأخضر (%)"},{"Edge softness (%)","Suavidad del borde (%)","Douceur des contours (%)","نعومة الحواف (%)"},
        {"Automatic captions","Subtítulos automáticos","Sous-titres automatiques","ترجمة نصية تلقائية"},{"Add caption","Añadir subtítulo","Ajouter un sous-titre","إضافة ترجمة نصية"},
        {"Edit captions","Editar subtítulos","Modifier les sous-titres","تحرير الترجمة النصية"},{"Add title","Añadir título","Ajouter un titre","إضافة عنوان"},
        {"Import logo or image","Importar logo o imagen","Importer un logo ou une image","استيراد شعار أو صورة"},
        {"Use last logo","Usar último logo","Utiliser le dernier logo","استخدام الشعار الأخير"},{"Edit graphics","Editar gráficos","Modifier les éléments","تحرير الرسومات"},
        {"Green-screen background","Fondo de pantalla verde","Arrière-plan du fond vert","خلفية الشاشة الخضراء"},
        {"Text","Texto","Texte","النص"},{"Bold","Negrita","Gras","عريض"},{"Colour","Color","Couleur","اللون"},
        {"Background","Fondo","Arrière-plan","الخلفية"},{"Horizontal position (%)","Posición horizontal (%)","Position horizontale (%)","الموضع الأفقي (%)"},
        {"Vertical position (%)","Posición vertical (%)","Position verticale (%)","الموضع الرأسي (%)"},
        {"Size (% of width)","Tamaño (% del ancho)","Taille (% de la largeur)","الحجم (% من العرض)"},{"Opacity (%)","Opacidad (%)","Opacité (%)","العتامة (%)"},
        {"Import music","Importar música","Importer de la musique","استيراد موسيقى"},{"Edit music","Editar música","Modifier la musique","تحرير الموسيقى"},
        {"Remove music","Quitar música","Supprimer la musique","إزالة الموسيقى"},{"Volume (%)","Volumen (%)","Volume (%)","مستوى الصوت (%)"},
        {"Timeline start (seconds)","Inicio en la línea de tiempo (segundos)","Début sur la timeline (secondes)","البداية على الخط الزمني (ثوانٍ)"},
        {"Fade in (seconds)","Entrada gradual (segundos)","Fondu d’entrée (secondes)","تلاشي الدخول (ثوانٍ)"},{"Fade out (seconds)","Salida gradual (segundos)","Fondu de sortie (secondes)","تلاشي الخروج (ثوانٍ)"},
        {"Video","Vídeo","Vidéo","الفيديو"},{"Sound","Sonido","Son","الصوت"},{"Original","Original","Original","الأصلي"},
        {"No projects yet. Import a video from your preferred camera.","Aún no hay proyectos. Importa un vídeo de tu cámara preferida.","Aucun projet. Importez une vidéo de votre caméra préférée.","لا توجد مشاريع بعد. استورد فيديو من الكاميرا التي تفضلها."},
        {"Changes saved on this phone","Cambios guardados en este teléfono","Modifications enregistrées sur ce téléphone","تم حفظ التغييرات على هذا الهاتف"},
        {"Pro test · purchases are disabled","Prueba Pro · compras desactivadas","Test Pro · achats désactivés","اختبار Pro · المشتريات معطلة"},
        {"Open teleprompter","Abrir teleprompter","Ouvrir le téléprompteur","فتح الملقّن"},
        {"Video editor","Editor de vídeo","Éditeur vidéo","محرر الفيديو"},
        {"Record with the teleprompter, then edit your video here.","Graba con el teleprompter y edita aquí el vídeo.","Enregistrez avec le téléprompteur, puis montez votre vidéo ici.","سجّل باستخدام الملقّن، ثم حرّر الفيديو هنا."},
        {"Edit a video","Editar un vídeo","Modifier une vidéo","تحرير فيديو"},
        {"How it works","Cómo funciona","Comment ça marche","طريقة الاستخدام"},
        {"No projects yet. Tap Edit a video to choose a recording.","Aún no hay proyectos. Toca Editar un vídeo para elegir una grabación.","Aucun projet. Touchez Modifier une vidéo pour choisir un enregistrement.","لا توجد مشاريع بعد. اضغط على تحرير فيديو لاختيار تسجيل."},
        {"Step 1 of 3: Record","Paso 1 de 3: Grabar","Étape 1 sur 3 : enregistrer","الخطوة 1 من 3: التسجيل"},
        {"Step 2 of 3: Import","Paso 2 de 3: Importar","Étape 2 sur 3 : importer","الخطوة 2 من 3: الاستيراد"},
        {"Step 3 of 3: Edit and export","Paso 3 de 3: Editar y exportar","Étape 3 sur 3 : monter et exporter","الخطوة 3 من 3: التحرير والتصدير"},
        {"Open the teleprompter and record with your preferred camera app.","Abre el teleprompter y graba con la aplicación de cámara que prefieras.","Ouvrez le téléprompteur et enregistrez avec l’application caméra de votre choix.","افتح الملقّن وسجّل باستخدام تطبيق الكاميرا المفضل لديك."},
        {"Return here, tap Edit a video, and choose the recording from your phone.","Vuelve aquí, toca Editar un vídeo y elige la grabación de tu teléfono.","Revenez ici, touchez Modifier une vidéo et choisissez l’enregistrement sur votre téléphone.","عُد إلى هنا، واضغط على تحرير فيديو، ثم اختر التسجيل من هاتفك."},
        {"Add or adjust captions, graphics, and music. Play clip checks the source; Edited preview shows the finished edits. Export to save or share.","Añade o ajusta subtítulos, gráficos y música. Reproducir clip comprueba el original; la vista previa editada muestra los cambios. Exporta para guardar o compartir.","Ajoutez ou modifiez les sous-titres, les éléments visuels et la musique. Lire le clip vérifie la source ; l’aperçu du montage montre les modifications. Exportez pour enregistrer ou partager.","أضف الترجمة النصية والرسومات والموسيقى أو عدّلها. تشغيل المقطع يعرض الأصل؛ والمعاينة تعرض التعديلات. صدّر للحفظ أو المشاركة."},
        {"Next","Siguiente","Suivant","التالي"},
        {"Previous","Anterior","Précédent","السابق"},
        {"Done","Listo","Terminé","تم"},
        {"Skip","Omitir","Ignorer","تخطي"},
        {"Finished video","Vídeo terminado","Vidéo terminée","الفيديو النهائي"},
        {"Attach to selected clip","Vincular al clip seleccionado","Lier au clip sélectionné","ربط بالمقطع المحدد"},
        {"White","Blanco","Blanc","أبيض"},{"Yellow","Amarillo","Jaune","أصفر"},{"Blue","Azul","Bleu","أزرق"},{"Pink","Rosa","Rose","وردي"},
        {"Black","Negro","Noir","أسود"},{"Transparent","Transparente","Transparent","شفاف"},
        {"Delete this project and its imported files?","¿Eliminar este proyecto y sus archivos importados?","Supprimer ce projet et ses fichiers importés ?","هل تريد حذف هذا المشروع وملفاته المستوردة؟"},
        {"Generating a preview uses the same renderer as export.","La vista previa usa el mismo motor que la exportación.","L’aperçu utilise le même moteur que l’exportation.","تستخدم المعاينة نفس محرك التصدير."},
        {"Select a clip first.","Selecciona un clip primero.","Sélectionnez d’abord un clip.","حدد مقطعًا أولاً."},
        {"Source times in selected clip; timing follows speed and reordering.","Tiempos del clip original; se ajustan al cambiar velocidad y orden.","Temps du clip source ; suit la vitesse et le réordonnancement.","أوقات المقطع الأصلي؛ تتبع تغييرات السرعة والترتيب."},
        {"Timeline times","Tiempos de la línea de tiempo","Temps sur la timeline","أوقات الخط الزمني"},
        {"Show throughout video","Mostrar en todo el vídeo","Afficher pendant toute la vidéo","إظهار طوال الفيديو"},
        {"Wait for the current job or cancel it first.","Espera al trabajo actual o cancélalo primero.","Attendez la tâche en cours ou annulez-la d’abord.","انتظر المهمة الحالية أو ألغها أولاً."},
        {"Import a video first.","Importa un vídeo primero.","Importez d’abord une vidéo.","استورد فيديو أولاً."},
        {"Import music first.","Importa música primero.","Importez d’abord de la musique.","استورد الموسيقى أولاً."},
        {"Import a logo first.","Importa un logo primero.","Importez d’abord un logo.","استورد شعارًا أولاً."},
        {"No items yet.","Aún no hay elementos.","Aucun élément pour le moment.","لا توجد عناصر بعد."},
        {"Starting…","Iniciando…","Démarrage…","جارٍ البدء…"},{"Starting","Iniciando","Démarrage","جارٍ البدء"},
        {"Saved.","Guardado.","Enregistré.","تم الحفظ."},{"Stopped","Detenido","Arrêté","متوقف"},
        {"Rendering video","Procesando vídeo","Rendu de la vidéo","جارٍ معالجة الفيديو"},
        {"Decoding first frame","Leyendo primer fotograma","Lecture de la première image","جارٍ قراءة الإطار الأول"},
        {"Configuring video encoder","Configurando codificador","Configuration de l’encodeur","جارٍ إعداد مُرمّز الفيديو"},
        {"Connecting encoder surface","Conectando superficie","Connexion de la surface","جارٍ توصيل سطح الترميز"},
        {"Starting video encoder","Iniciando codificador","Démarrage de l’encodeur","جارٍ بدء مُرمّز الفيديو"},
        {"Preparing audio","Preparando audio","Préparation du son","جارٍ تجهيز الصوت"},
        {"Mixing sound","Mezclando sonido","Mixage du son","جارٍ مزج الصوت"},
        {"Finishing MP4","Finalizando MP4","Finalisation du MP4","جارٍ إنهاء MP4"},
        {"Video ready","Vídeo listo","Vidéo prête","الفيديو جاهز"},{"Captions ready","Subtítulos listos","Sous-titres prêts","الترجمة النصية جاهزة"},
        {"Complete","Completado","Terminé","مكتمل"},{"Cancelled.","Cancelado.","Annulé.","تم الإلغاء."},
        {"Downloading speech pack (about 40 MB)","Descargando paquete de voz (unos 40 MB)","Téléchargement du pack vocal (environ 40 Mo)","جارٍ تنزيل حزمة الكلام (حوالي 40 ميغابايت)"},
        {"Downloading speech pack","Descargando paquete de voz","Téléchargement du pack vocal","جارٍ تنزيل حزمة الكلام"},
        {"Installing speech pack","Instalando paquete de voz","Installation du pack vocal","جارٍ تثبيت حزمة الكلام"},
        {"Reading clip audio","Leyendo audio del clip","Lecture du son du clip","جارٍ قراءة صوت المقطع"},
        {"Creating local captions","Creando subtítulos locales","Création des sous-titres locaux","جارٍ إنشاء الترجمة النصية محليًا"},
        {"Keep at least 0.1 seconds of video.","Conserva al menos 0,1 segundos de vídeo.","Conservez au moins 0,1 seconde de vidéo.","احتفظ بما لا يقل عن 0.1 ثانية من الفيديو."},
        {"The crop area is too small.","El área de recorte es demasiado pequeña.","La zone de recadrage est trop petite.","منطقة القص صغيرة جدًا."},
        {"End must come after start.","El final debe ser posterior al inicio.","La fin doit être après le début.","يجب أن تكون النهاية بعد البداية."},
        {"Enter some text.","Escribe algún texto.","Saisissez du texte.","أدخل نصًا."},
        {"Download a speech pack (about 40 MB) if needed, then caption this clip on your phone. This replaces this clip’s captions. Arabic: use Add caption.",
         "Descarga un paquete de voz (unos 40 MB) si hace falta para subtitular este clip en tu teléfono. Se reemplazan sus subtítulos. Árabe: usa Añadir subtítulo.",
         "Téléchargez un pack vocal (environ 40 Mo) si nécessaire, puis créez les sous-titres sur votre téléphone. Les sous-titres du clip seront remplacés. Arabe : utilisez Ajouter un sous-titre.",
         "نزّل حزمة كلام (حوالي 40 ميغابايت) إذا لزم الأمر، ثم أنشئ الترجمة النصية على هاتفك. سيستبدل ذلك ترجمة هذا المقطع. للعربية: استخدم إضافة ترجمة نصية."}
    };
    static String t(Context context,String source){String code=AppLanguage.current(context);int col="es".equals(code)?1:"fr".equals(code)?2:"ar".equals(code)?3:0;
        for(String[] row:WORDS)if(row[0].equals(source))return row[col];return AppLanguage.t(context,source);}
}
