package com.costavong.promptoverlay.pro;
import android.content.Context;
import com.costavong.promptoverlay.AppLanguage;
final class ProStrings {
    private static final String[][] WORDS={
        {"Close","Cerrar","Fermer","إغلاق"},
        {"Projects","Proyectos","Projets","المشاريع"},{"New project","Nuevo proyecto","Nouveau projet","مشروع جديد"},
        {"Teleprompter","Teleprompter","Téléprompteur","الملقّن"},{"Language","Idioma","Langue","اللغة"},
        {"Import video","Importar vídeo","Importer une vidéo","استيراد فيديو"},{"Rename","Renombrar","Renommer","إعادة تسمية"},
        {"Delete","Eliminar","Supprimer","حذف"},{"Open","Abrir","Ouvrir","فتح"},{"Back","Atrás","Retour","رجوع"},
        {"Save","Guardar","Enregistrer","حفظ"},{"Cancel","Cancelar","Annuler","إلغاء"},{"Clips","Clips","Clips","المقاطع"},
        {"Captions","Subtítulos","Sous-titres","الترجمة النصية"},{"Graphics","Gráficos","Éléments visuels","الرسومات"},
        {"Graphics help","Ayuda de gráficos","Aide sur les éléments visuels","مساعدة الرسومات"},
        {"Help information","Información de ayuda","Informations d’aide","معلومات المساعدة"},
        {"Rename help","Change the name shown for this project. It does not rename the original video file.","Cambia el nombre de este proyecto. No cambia el nombre del archivo de vídeo original.","Modifiez le nom affiché pour ce projet. Cela ne renomme pas le fichier vidéo d’origine.","غيّر الاسم المعروض لهذا المشروع. لا يغيّر ذلك اسم ملف الفيديو الأصلي."},
        {"Import video help","Add another video from your phone or a connected file provider. It becomes another clip in this project’s timeline.","Añade otro vídeo desde tu teléfono o un proveedor de archivos conectado. Se convierte en otro clip de la línea de tiempo del proyecto.","Ajoutez une autre vidéo depuis votre téléphone ou un fournisseur de fichiers connecté. Elle devient un clip supplémentaire dans la timeline du projet.","أضف فيديو آخر من هاتفك أو من موفّر ملفات متصل. سيصبح مقطعًا إضافيًا في الخط الزمني لهذا المشروع."},
        {"Play clip help","Plays the selected original clip immediately. It does not include edits, captions, graphics, or music. Use Edited preview to see the full result.","Reproduce inmediatamente el clip original seleccionado. No incluye ediciones, subtítulos, gráficos ni música. Usa Vista previa editada para ver el resultado completo.","Lit immédiatement le clip source sélectionné. La lecture n’inclut pas les modifications, les sous-titres, les éléments visuels ou la musique. Utilisez Aperçu du montage pour voir le résultat complet.","يشغّل المقطع الأصلي المحدد فورًا. لا يتضمن التعديلات أو الترجمة النصية أو الرسومات أو الموسيقى. استخدم معاينة الفيديو المعدّل لرؤية النتيجة كاملة."},
        {"Clips help","Edit the selected clip, split it at the playhead, move it earlier or later, or delete it. Edit selected clip includes trim, speed, crop, picture, and sound settings.","Edita el clip seleccionado, divídelo en el cabezal de reproducción, muévelo antes o después, o elimínalo. Editar clip seleccionado incluye opciones de recorte, velocidad, encuadre, imagen y sonido.","Modifiez le clip sélectionné, scindez-le au curseur, déplacez-le ou supprimez-le. Modifier le clip sélectionné permet de régler le découpage, la vitesse, le cadrage, l’image et le son.","حرّر المقطع المحدد أو قسّمه عند موضع التشغيل أو انقله أو احذفه. يتيح تحرير المقطع المحدد ضبط القص والسرعة والإطار والصورة والصوت."},
        {"Captions help","For the selected clip, create automatic captions in English, Spanish, or French, add captions manually, or edit existing captions. Arabic captions are added manually.","Para el clip seleccionado, crea subtítulos automáticos en inglés, español o francés, añádelos manualmente o edita los existentes. Los subtítulos en árabe se añaden manualmente.","Pour le clip sélectionné, créez des sous-titres automatiques en anglais, espagnol ou français, ajoutez-les manuellement ou modifiez-les. Les sous-titres arabes s’ajoutent manuellement.","للمقطع المحدد، أنشئ ترجمة نصية تلقائية بالإنجليزية أو الإسبانية أو الفرنسية، أو أضفها يدويًا أو حرّر الموجودة. تُضاف الترجمة العربية يدويًا."},
        {"Music help","Import one music track, then adjust its trim, timeline position, volume, and fade in or fade out. You can remove it at any time.","Importa una pista musical y ajusta su recorte, posición en la línea de tiempo, volumen y fundidos de entrada o salida. Puedes quitarla cuando quieras.","Importez une piste musicale, puis réglez son découpage, sa position dans la timeline, son volume et ses fondus d’entrée ou de sortie. Vous pouvez la supprimer à tout moment.","استورد مقطعًا موسيقيًا واحدًا، ثم اضبط قصّه وموضعه على الخط الزمني ومستوى صوته وتلاشي دخوله أو خروجه. يمكنك إزالته في أي وقت."},
        {"Format help","Choose the shape of the finished video: original, vertical 9:16, horizontal 16:9, square 1:1, or 4:5. Export separately lets you choose 720p or 1080p.","Elige la forma del vídeo final: original, vertical 9:16, horizontal 16:9, cuadrado 1:1 o 4:5. Al exportar puedes elegir 720p o 1080p.","Choisissez le format de la vidéo finale : original, vertical 9:16, horizontal 16:9, carré 1:1 ou 4:5. L’exportation permet de choisir 720p ou 1080p.","اختر شكل الفيديو النهائي: الأصلي أو عمودي 9:16 أو أفقي 16:9 أو مربع 1:1 أو 4:5. يتيح التصدير اختيار 720p أو 1080p."},
        {"Preview help","Edited preview renders a watchable version with your edits, captions, graphics, and music. It uses the same renderer as export and may take a little time.","La vista previa editada genera una versión para ver con tus cambios, subtítulos, gráficos y música. Usa el mismo motor que la exportación y puede tardar un poco.","L’aperçu du montage génère une version à regarder avec vos modifications, sous-titres, éléments visuels et musique. Il utilise le même moteur que l’exportation et peut prendre un peu de temps.","تنشئ معاينة الفيديو المعدّل نسخة قابلة للمشاهدة تتضمن تعديلاتك والترجمة النصية والرسومات والموسيقى. تستخدم محرك التصدير نفسه وقد تستغرق بعض الوقت."},
        {"Export help","Choose Export, then select 720p or 1080p MP4. When rendering finishes, preview the result, save it to your phone, or share it.","Elige Exportar y selecciona MP4 de 720p o 1080p. Cuando termine el procesamiento, previsualiza el resultado, guárdalo en tu teléfono o compártelo.","Choisissez Exporter, puis sélectionnez MP4 720p ou 1080p. Une fois le rendu terminé, prévisualisez le résultat, enregistrez-le sur votre téléphone ou partagez-le.","اختر تصدير، ثم حدّد MP4 بدقة 720p أو 1080p. بعد اكتمال المعالجة، عاين النتيجة أو احفظها على هاتفك أو شاركها."},
        {"Got it","Entendido","Compris","حسنًا"},
        {"Add a title, logo, or image over your video. Choose Add title or Import logo or image. Use Edit graphics to change when it appears, its position, size, and opacity. Green-screen background lets you choose an image to replace the green background.",
         "Añade un título, logotipo o imagen sobre el vídeo. Elige Añadir título o Importar logotipo o imagen. Usa Editar gráficos para cambiar cuándo aparece, su posición, tamaño y opacidad. Fondo de pantalla verde permite elegir una imagen para reemplazar el fondo verde.",
         "Ajoutez un titre, un logo ou une image sur la vidéo. Choisissez Ajouter un titre ou Importer un logo ou une image. Utilisez Modifier les éléments pour régler son moment d’apparition, sa position, sa taille et son opacité. Arrière-plan du fond vert permet de choisir une image pour remplacer le fond vert.",
         "أضف عنوانًا أو شعارًا أو صورة فوق الفيديو. اختر إضافة عنوان أو استيراد شعار أو صورة. استخدم تحرير الرسومات لتغيير وقت ظهورها وموضعها وحجمها وشفافيتها. تتيح خلفية الشاشة الخضراء اختيار صورة لاستبدال الخلفية الخضراء."},
        {"Music","Música","Musique","الموسيقى"},{"Format","Formato","Format","التنسيق"},
        {"Preview","Vista previa","Aperçu","معاينة"},{"Export","Exportar","Exporter","تصدير"},
        {"Play clip","Reproducir clip","Lire le clip","تشغيل المقطع"},{"Pause","Pausar","Pause","إيقاف مؤقت"},
        {"Edited preview","Vista previa editada","Aperçu du montage","معاينة الفيديو المعدّل"},
        {"Play clip starts immediately. Edited preview includes captions, graphics and music.",
         "Reproducir clip empieza al instante. La vista previa editada incluye subtítulos, gráficos y música.",
         "La lecture du clip démarre immédiatement. L’aperçu du montage inclut les sous-titres, les éléments visuels et la musique.",
         "يبدأ تشغيل المقطع فورًا. تتضمن معاينة الفيديو المعدّل الترجمة النصية والرسومات والموسيقى."},
        {"Share","Compartir","Partager","مشاركة"},{"Save video","Guardar vídeo","Enregistrer la vidéo","حفظ الفيديو"},
        {"Project name","Nombre del proyecto","Nom du projet","اسم المشروع"},{"Edit selected clip","Editar clip seleccionado","Modifier le clip sélectionné","تحرير المقطع المحدد"},
        {"Split at playhead","Dividir aquí","Scinder au curseur","تقسيم عند المؤشر"},{"Move earlier","Mover antes","Déplacer avant","نقل إلى الأمام"},
        {"Move later","Mover después","Déplacer après","نقل إلى الخلف"},{"Delete clip","Eliminar clip","Supprimer le clip","حذف المقطع"},
        {"Start (seconds)","Inicio (segundos)","Début (secondes)","البداية (ثوانٍ)"},{"End (seconds)","Fin (segundos)","Fin (secondes)","النهاية (ثوانٍ)"},
        {"Speed","Velocidad","Vitesse","السرعة"},{"Crossfade into this clip (seconds)","Fundido a este clip (segundos)","Fondu vers ce clip (secondes)","تلاشي إلى هذا المقطع (ثوانٍ)"},
        {"Original sound volume (%)","Volumen original (%)","Volume du son original (%)","مستوى الصوت الأصلي (%)"},
        {"Mute original sound","Silenciar sonido original","Couper le son original","كتم الصوت الأصلي"},
        {"Brightness (-100 to 100)","Brillo (-100 a 100)","Luminosité (-100 à 100)","السطوع (-100 إلى 100)"},
        {"Contrast (%)","Contraste (%)","Contraste (%)","التباين (%)"},{"Saturation (%)","Saturación (%)","Saturation (%)","التشبع (%)"},
        {"Temperature (-100 to 100)","Temperatura (-100 a 100)","Température (-100 à 100)","الحرارة (-100 إلى 100)"},
        {"Crop left (%)","Recorte izquierdo (%)","Recadrage gauche (%)","قص اليسار (%)"},{"Crop top (%)","Recorte superior (%)","Recadrage haut (%)","قص الأعلى (%)"},
        {"Crop right (%)","Recorte derecho (%)","Recadrage droite (%)","قص اليمين (%)"},{"Crop bottom (%)","Recorte inferior (%)","Recadrage bas (%)","قص الأسفل (%)"},
        {"Green screen (experimental)","Pantalla verde (experimental)","Fond vert (expérimental)","الشاشة الخضراء (تجريبية)"},
        {"Green threshold (%)","Umbral verde (%)","Seuil du vert (%)","عتبة الأخضر (%)"},{"Edge softness (%)","Suavidad del borde (%)","Douceur des contours (%)","نعومة الحواف (%)"},
        {"Automatic captions","Subtítulos automáticos","Sous-titres automatiques","ترجمة نصية تلقائية"},{"Add caption","Añadir subtítulo","Ajouter un sous-titre","إضافة ترجمة نصية"},
        {"Edit captions","Editar subtítulos","Modifier les sous-titres","تحرير الترجمة النصية"},{"Add title","Añadir título","Ajouter un titre","إضافة عنوان"},
        {"Import logo or image","Importar logo o imagen","Importer un logo ou une image","استيراد شعار أو صورة"},
        {"Use last logo","Usar último logo","Utiliser le dernier logo","استخدام الشعار الأخير"},{"Edit graphics","Editar gráficos","Modifier les éléments","تحرير الرسومات"},
        {"Green-screen background","Fondo de pantalla verde","Arrière-plan du fond vert","خلفية الشاشة الخضراء"},
        {"Text","Texto","Texte","النص"},{"Bold","Negrita","Gras","عريض"},{"Colour","Color","Couleur","اللون"},
        {"Background","Fondo","Arrière-plan","الخلفية"},{"Horizontal position (%)","Posición horizontal (%)","Position horizontale (%)","الموضع الأفقي (%)"},
        {"Vertical position (%)","Posición vertical (%)","Position verticale (%)","الموضع الرأسي (%)"},
        {"Size (% of width)","Tamaño (% del ancho)","Taille (% de la largeur)","الحجم (% من العرض)"},{"Opacity (%)","Opacidad (%)","Opacité (%)","العتامة (%)"},
        {"Import music","Importar música","Importer de la musique","استيراد موسيقى"},{"Edit music","Editar música","Modifier la musique","تحرير الموسيقى"},
        {"Remove music","Quitar música","Supprimer la musique","إزالة الموسيقى"},{"Volume (%)","Volumen (%)","Volume (%)","مستوى الصوت (%)"},
        {"Timeline start (seconds)","Inicio en la línea de tiempo (segundos)","Début sur la timeline (secondes)","البداية على الخط الزمني (ثوانٍ)"},
        {"Fade in (seconds)","Entrada gradual (segundos)","Fondu d’entrée (secondes)","تلاشي الدخول (ثوانٍ)"},{"Fade out (seconds)","Salida gradual (segundos)","Fondu de sortie (secondes)","تلاشي الخروج (ثوانٍ)"},
        {"Video","Vídeo","Vidéo","الفيديو"},{"Sound","Sonido","Son","الصوت"},{"Original","Original","Original","الأصلي"},
        {"No projects yet. Import a video from your preferred camera.","Aún no hay proyectos. Importa un vídeo de tu cámara preferida.","Aucun projet. Importez une vidéo de votre caméra préférée.","لا توجد مشاريع بعد. استورد فيديو من الكاميرا التي تفضلها."},
        {"Changes saved on this phone","Cambios guardados en este teléfono","Modifications enregistrées sur ce téléphone","تم حفظ التغييرات على هذا الهاتف"},
        {"Pro test · purchases are disabled","Prueba Pro · compras desactivadas","Test Pro · achats désactivés","اختبار Pro · المشتريات معطلة"},
        {"Open teleprompter","Abrir teleprompter","Ouvrir le téléprompteur","فتح الملقّن"},
        {"Video editor","Editor de vídeo","Éditeur vidéo","محرر الفيديو"},
        {"Edit a video","Editar un vídeo","Modifier une vidéo","تحرير فيديو"},
        {"No projects yet. Tap Edit a video to choose a recording.","Aún no hay proyectos. Toca Editar un vídeo para elegir una grabación.","Aucun projet. Touchez Modifier une vidéo pour choisir un enregistrement.","لا توجد مشاريع بعد. اضغط على تحرير فيديو لاختيار تسجيل."},
        {"Add or adjust captions, graphics, and music. Play clip checks the source; Edited preview shows the finished edits. Export to save or share.","Añade o ajusta subtítulos, gráficos y música. Reproducir clip comprueba el original; la vista previa editada muestra los cambios. Exporta para guardar o compartir.","Ajoutez ou modifiez les sous-titres, les éléments visuels et la musique. Lire le clip vérifie la source ; l’aperçu du montage montre les modifications. Exportez pour enregistrer ou partager.","أضف الترجمة النصية والرسومات والموسيقى أو عدّلها. تشغيل المقطع يعرض الأصل؛ والمعاينة تعرض التعديلات. صدّر للحفظ أو المشاركة."},
        {"Finished video","Vídeo terminado","Vidéo terminée","الفيديو النهائي"},
        {"Attach to selected clip","Vincular al clip seleccionado","Lier au clip sélectionné","ربط بالمقطع المحدد"},
        {"White","Blanco","Blanc","أبيض"},{"Yellow","Amarillo","Jaune","أصفر"},{"Blue","Azul","Bleu","أزرق"},{"Pink","Rosa","Rose","وردي"},
        {"Black","Negro","Noir","أسود"},{"Transparent","Transparente","Transparent","شفاف"},
        {"Delete this project and its imported files?","¿Eliminar este proyecto y sus archivos importados?","Supprimer ce projet et ses fichiers importés ?","هل تريد حذف هذا المشروع وملفاته المستوردة؟"},
        {"Generating a preview uses the same renderer as export.","La vista previa usa el mismo motor que la exportación.","L’aperçu utilise le même moteur que l’exportation.","تستخدم المعاينة نفس محرك التصدير."},
        {"Select a clip first.","Selecciona un clip primero.","Sélectionnez d’abord un clip.","حدد مقطعًا أولاً."},
        {"Source times in selected clip; timing follows speed and reordering.","Tiempos del clip original; se ajustan al cambiar velocidad y orden.","Temps du clip source ; suit la vitesse et le réordonnancement.","أوقات المقطع الأصلي؛ تتبع تغييرات السرعة والترتيب."},
        {"Timeline times","Tiempos de la línea de tiempo","Temps sur la timeline","أوقات الخط الزمني"},
        {"Show throughout video","Mostrar en todo el vídeo","Afficher pendant toute la vidéo","إظهار طوال الفيديو"},
        {"Wait for the current job or cancel it first.","Espera al trabajo actual o cancélalo primero.","Attendez la tâche en cours ou annulez-la d’abord.","انتظر المهمة الحالية أو ألغها أولاً."},
        {"Import a video first.","Importa un vídeo primero.","Importez d’abord une vidéo.","استورد فيديو أولاً."},
        {"Import music first.","Importa música primero.","Importez d’abord de la musique.","استورد الموسيقى أولاً."},
        {"Import a logo first.","Importa un logo primero.","Importez d’abord un logo.","استورد شعارًا أولاً."},
        {"No items yet.","Aún no hay elementos.","Aucun élément pour le moment.","لا توجد عناصر بعد."},
        {"Starting…","Iniciando…","Démarrage…","جارٍ البدء…"},{"Starting","Iniciando","Démarrage","جارٍ البدء"},
        {"Saved.","Guardado.","Enregistré.","تم الحفظ."},{"Stopped","Detenido","Arrêté","متوقف"},
        {"Rendering video","Procesando vídeo","Rendu de la vidéo","جارٍ معالجة الفيديو"},
        {"Decoding first frame","Leyendo primer fotograma","Lecture de la première image","جارٍ قراءة الإطار الأول"},
        {"Configuring video encoder","Configurando codificador","Configuration de l’encodeur","جارٍ إعداد مُرمّز الفيديو"},
        {"Connecting encoder surface","Conectando superficie","Connexion de la surface","جارٍ توصيل سطح الترميز"},
        {"Starting video encoder","Iniciando codificador","Démarrage de l’encodeur","جارٍ بدء مُرمّز الفيديو"},
        {"Preparing audio","Preparando audio","Préparation du son","جارٍ تجهيز الصوت"},
        {"Mixing sound","Mezclando sonido","Mixage du son","جارٍ مزج الصوت"},
        {"Finishing MP4","Finalizando MP4","Finalisation du MP4","جارٍ إنهاء MP4"},
        {"Video ready","Vídeo listo","Vidéo prête","الفيديو جاهز"},{"Captions ready","Subtítulos listos","Sous-titres prêts","الترجمة النصية جاهزة"},
        {"Complete","Completado","Terminé","مكتمل"},{"Cancelled.","Cancelado.","Annulé.","تم الإلغاء."},
        {"Downloading speech pack (about 40 MB)","Descargando paquete de voz (unos 40 MB)","Téléchargement du pack vocal (environ 40 Mo)","جارٍ تنزيل حزمة الكلام (حوالي 40 ميغابايت)"},
        {"Downloading speech pack","Descargando paquete de voz","Téléchargement du pack vocal","جارٍ تنزيل حزمة الكلام"},
        {"Installing speech pack","Instalando paquete de voz","Installation du pack vocal","جارٍ تثبيت حزمة الكلام"},
        {"Reading clip audio","Leyendo audio del clip","Lecture du son du clip","جارٍ قراءة صوت المقطع"},
        {"Creating local captions","Creando subtítulos locales","Création des sous-titres locaux","جارٍ إنشاء الترجمة النصية محليًا"},
        {"Keep at least 0.1 seconds of video.","Conserva al menos 0,1 segundos de vídeo.","Conservez au moins 0,1 seconde de vidéo.","احتفظ بما لا يقل عن 0.1 ثانية من الفيديو."},
        {"The crop area is too small.","El área de recorte es demasiado pequeña.","La zone de recadrage est trop petite.","منطقة القص صغيرة جدًا."},
        {"End must come after start.","El final debe ser posterior al inicio.","La fin doit être après le début.","يجب أن تكون النهاية بعد البداية."},
        {"Enter some text.","Escribe algún texto.","Saisissez du texte.","أدخل نصًا."},
        {"Download a speech pack (about 40 MB) if needed, then caption this clip on your phone. This replaces this clip’s captions. Arabic: use Add caption.",
         "Descarga un paquete de voz (unos 40 MB) si hace falta para subtitular este clip en tu teléfono. Se reemplazan sus subtítulos. Árabe: usa Añadir subtítulo.",
         "Téléchargez un pack vocal (environ 40 Mo) si nécessaire, puis créez les sous-titres sur votre téléphone. Les sous-titres du clip seront remplacés. Arabe : utilisez Ajouter un sous-titre.",
         "نزّل حزمة كلام (حوالي 40 ميغابايت) إذا لزم الأمر، ثم أنشئ الترجمة النصية على هاتفك. سيستبدل ذلك ترجمة هذا المقطع. للعربية: استخدم إضافة ترجمة نصية."},
        {"Choose what you want to do","Elige qué quieres hacer","Choisissez ce que vous voulez faire","اختر ما تريد القيام به"},
        {"Use the teleprompter while recording, or edit a video from your camera.","Usa el teleprompter mientras grabas o edita un vídeo de tu cámara.","Utilisez le téléprompteur pendant l’enregistrement ou montez une vidéo de votre caméra.","استخدم الملقّن أثناء التسجيل أو حرّر فيديو من كاميرتك."},
        {"Your projects","Tus proyectos","Vos projets","مشاريعك"},
        {"Rate app","Valorar la app","Évaluer l’application","قيّم التطبيق"},
        {"Enjoying Prompt Overlay?","¿Te gusta Prompt Overlay?","Vous appréciez Prompt Overlay ?","هل تستمتع باستخدام Prompt Overlay؟"},
        {"If Prompt Overlay has been useful, would you rate it on Google Play?","Si Prompt Overlay te ha sido útil, ¿la valorarías en Google Play?","Si Prompt Overlay vous a été utile, pourriez-vous la noter sur Google Play ?","إذا كان Prompt Overlay مفيدًا لك، هل تقيّمه على Google Play؟"},
        {"Rate us","Valóranos","Nous noter","قيّمنا"},
        {"Not now","Ahora no","Pas maintenant","ليس الآن"},
    };
    static String t(Context context,String source){String code=AppLanguage.current(context);int col="es".equals(code)?1:"fr".equals(code)?2:"ar".equals(code)?3:0;
        for(String[] row:WORDS)if(row[0].equals(source))return row[col];return AppLanguage.t(context,source);}
}
